# Generated by Django 4.1.1 on 2022-09-28 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'estado_civil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('url', models.TextField()),
                ('nivel', models.IntegerField(default=1)),
                ('icono', models.TextField()),
                ('orden', models.IntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('modulo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_modulo_padre', to='users.modulo')),
            ],
            options={
                'db_table': 'modulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'nacionalidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(editable=False)),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfil')),
            ],
            options={
                'db_table': 'perfil_rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=11, unique=True)),
                ('nombre', models.TextField()),
                ('apellido_paterno', models.TextField()),
                ('apellido_materno', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('email_personal', models.TextField(blank=True, null=True)),
                ('email_institucional', models.TextField()),
                ('prs_celular', models.BigIntegerField(blank=True, null=True)),
                ('prs_telefono', models.BigIntegerField(blank=True, null=True)),
                ('ind_pasaporte', models.BooleanField(default=False)),
                ('pasaporte', models.TextField(blank=True, default=None, null=True)),
                ('prs_fecha_defuncion', models.DateTimeField(blank=True, null=True)),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.estadocivil')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.nacionalidad')),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('sxo_mnemonico', models.TextField()),
            ],
            options={
                'db_table': 'sexo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoModulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'tipo_modulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('usuario', models.TextField()),
                ('contrasena', models.TextField()),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.persona')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonaPerfilRol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('perfil_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilrol')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.persona')),
            ],
            options={
                'db_table': 'persona_perfil_rol',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sexo'),
        ),
        migrations.AddField(
            model_name='perfilrol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rol'),
        ),
        migrations.CreateModel(
            name='ModuloRol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ind_get', models.BooleanField(default=False)),
                ('ind_post', models.BooleanField(default=False)),
                ('ind_put', models.BooleanField(default=False)),
                ('ind_delete', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rol')),
            ],
            options={
                'db_table': 'modulo_rol',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='tipo_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipomodulo'),
        ),
    ]
