version: '3'
services:
  db_postgres:
    image: 'postgres:11.5'
    restart: always
    volumes:
    - 'postgres_data:/var/lib/postgresql/data'
    environment:
    - POSTGRES_USER=nega
    - POSTGRES_PASSWORD=Nega6456519
    ports:
    - '5432:5432'
    container_name: db_postgres
  
  django_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres
    container_name: django_app
    command: bash -c "
        python manage.py makemigrations
        && python manage.py migrate 
        && python manage.py runserver 0.0.0.0:8000"
  
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app
    container_name: nginx

volumes:
  .:
  postgres_data:
  static: